// Exhaustive planning catalog for the future ECS architecture.
// This file intentionally contains names only. It does not implement behavior.

export const COMPONENTS = {
  core: [
    "EntityId",
    "EntityType",
    "EntityTags",
    "DefinitionReference",
    "Namespace",
    "SchemaVersion",
    "SerializationVersion",
    "CreatedAt",
    "UpdatedAt",
    "EnabledState",
    "LifecycleState",
    "ParentEntity",
    "ChildEntities",
    "Ownership",
    "Controller",
  ],

  creatureIdentity: [
    "CreatureTag",
    "MonsterTag",
    "NpcTag",
    "SelectableTag",
    "Identity",
    "Name",
    "Title",
    "Description",
    "Biography",
    "CreatureType",
    "CreatureSubtypes",
    "CreatureTags",
    "Alignment",
    "Disposition",
    "FactionMembership",
    "Relationships",
    "Reputation",
    "Languages",
    "CommunicationModes",
  ],

  physical: [
    "Size",
    "Appearance",
    "Body",
    "Anatomy",
    "Position",
    "Facing",
    "MovementModes",
    "SpaceOccupied",
    "Reach",
    "Encumbrance",
    "CarryingCapacity",
    "Weight",
    "Height",
    "Age",
    "LocomotionState",
    "Posture",
    "MountedState",
    "Mount",
    "Rider",
  ],

  abilities: [
    "AbilityScores",
    "AbilityModifiers",
    "Strength",
    "Dexterity",
    "Constitution",
    "Intelligence",
    "Wisdom",
    "Charisma",
    "ProficiencyBonus",
    "InitiativeModifier",
    "PassivePerception",
    "PassiveInsight",
    "PassiveInvestigation",
  ],

  proficiencies: [
    "Proficiencies",
    "SkillProficiencies",
    "SavingThrowProficiencies",
    "ToolProficiencies",
    "WeaponProficiencies",
    "ArmorProficiencies",
    "LanguageProficiencies",
    "Expertise",
    "HalfProficiency",
    "ProficiencyOverrides",
  ],

  vitality: [
    "HitPoints",
    "MaximumHitPoints",
    "CurrentHitPoints",
    "TemporaryHitPoints",
    "HitDice",
    "DeathState",
    "DeathSavingThrows",
    "StabilizationState",
    "UnconsciousState",
    "Exhaustion",
    "HealingModifiers",
    "RecoveryResources",
    "RestState",
    "ShortRestResources",
    "LongRestResources",
  ],

  defense: [
    "ArmorClass",
    "ArmorClassSources",
    "NaturalArmor",
    "ShieldState",
    "CoverState",
    "DamageResistances",
    "DamageVulnerabilities",
    "DamageImmunities",
    "ConditionImmunities",
    "SavingThrowModifiers",
    "DefensiveReactions",
    "DamageReduction",
    "DamageThreshold",
    "EvasionRules",
  ],

  perception: [
    "Senses",
    "Vision",
    "Darkvision",
    "Blindsight",
    "Tremorsense",
    "Truesight",
    "Hearing",
    "Smell",
    "PerceptionRange",
    "KnownEntities",
    "VisibleEntities",
    "DetectedEntities",
    "HiddenState",
    "StealthState",
    "Memory",
    "Knowledge",
  ],

  combat: [
    "Combatant",
    "BattleParticipant",
    "Initiative",
    "TurnOrder",
    "TurnState",
    "RoundState",
    "ActionEconomy",
    "ActionPoints",
    "BonusActionState",
    "ReactionState",
    "MovementBudget",
    "PreparedAction",
    "DodgeState",
    "DisengageState",
    "DashState",
    "HelpState",
    "SearchState",
    "ReadyState",
    "Concentration",
    "TargetingState",
    "ThreatenedState",
    "FlankingState",
    "GrappledState",
    "GrapplingState",
    "RestrainedState",
    "ProneState",
    "SurprisedState",
    "CombatLogReference",
  ],

  capabilities: [
    "Traits",
    "Features",
    "Feats",
    "Actions",
    "BonusActions",
    "Reactions",
    "LegendaryActions",
    "LairActions",
    "PassiveEffects",
    "TriggeredEffects",
    "Auras",
    "Transformations",
    "Summoning",
    "LimitedUses",
    "RechargeRules",
    "UsageCounters",
    "Cooldowns",
    "ActionSet",
    "ReactionSet",
    "TriggerSet",
  ],

  magic: [
    "Spellcasting",
    "InnateSpellcasting",
    "SpellLists",
    "KnownSpells",
    "PreparedSpells",
    "Spellbook",
    "Cantrips",
    "SpellSlots",
    "PactSlots",
    "RitualCasting",
    "SpellcastingAbility",
    "SpellSaveDifficultyClass",
    "SpellAttackBonus",
    "SpellcastingFocus",
    "MaterialComponents",
    "SomaticComponents",
    "VerbalComponents",
    "MagicCharges",
    "ConcentrationState",
    "ActiveSpellEffects",
  ],

  inventory: [
    "Inventory",
    "Equipment",
    "EquippedWeapons",
    "EquippedArmor",
    "EquippedShield",
    "Attunement",
    "Currency",
    "Containers",
    "ItemCharges",
    "ItemOwnership",
    "ItemDurability",
    "ItemCondition",
    "LootProfile",
    "TreasureProfile",
    "Consumables",
    "Ammunition",
    "QuestItems",
  ],

  progression: [
    "Experience",
    "CharacterLevel",
    "ChallengeRating",
    "ClassProgression",
    "ClassLevels",
    "RaceSelection",
    "SubraceSelection",
    "BackgroundSelection",
    "ClassSelection",
    "SubclassSelection",
    "MulticlassState",
    "CharacterBuild",
    "BuildHistory",
    "AdvancementRules",
    "AppliedGrants",
    "PendingChoices",
    "ResolvedChoices",
    "Milestones",
    "Inspiration",
  ],

  conditionsAndEffects: [
    "Conditions",
    "ActiveEffects",
    "Modifiers",
    "EffectSources",
    "EffectDurations",
    "EffectStacks",
    "EffectImmunities",
    "Diseases",
    "Poisons",
    "Curses",
    "Blessings",
    "Charms",
    "Madness",
    "EnvironmentalEffects",
    "TransformationEffects",
    "TemporaryOverrides",
  ],

  resources: [
    "Resources",
    "ResourcePools",
    "ResourceMaximums",
    "ResourceRecoveryRules",
    "ResourceCosts",
    "ResourceRegeneration",
    "ResourceLocks",
    "HitDiePool",
    "KiPool",
    "SorceryPointPool",
    "RageUses",
    "WildShapeUses",
    "ChannelDivinityUses",
    "SuperiorityDice",
    "InspirationDice",
  ],

  ai: [
    "PlayerControlled",
    "AIControlled",
    "BehaviorProfile",
    "Goals",
    "Motivations",
    "Personality",
    "Ideals",
    "Bonds",
    "Flaws",
    "Tactics",
    "ThreatAssessment",
    "TargetPriorities",
    "Morale",
    "FearProfile",
    "AggressionProfile",
    "CurrentIntent",
    "IntentHistory",
    "DecisionContext",
    "DecisionWeights",
    "KnownThreats",
    "KnownAllies",
    "KnownObjectives",
  ],

  scene: [
    "SceneTag",
    "SceneType",
    "SceneState",
    "SceneParticipants",
    "SceneObjectives",
    "SceneRules",
    "SceneHistory",
    "Location",
    "Zone",
    "Terrain",
    "Weather",
    "TimeOfDay",
    "LightLevel",
    "Visibility",
    "AmbientConditions",
    "EncounterState",
    "BattleState",
    "ExplorationState",
    "SocialState",
    "TravelState",
    "DowntimeState",
  ],

  worldObjects: [
    "ItemTag",
    "ObjectTag",
    "DoorTag",
    "ContainerTag",
    "TrapTag",
    "HazardTag",
    "TerrainTag",
    "LightSourceTag",
    "PortalTag",
    "VehicleTag",
    "StructureTag",
    "DoorState",
    "LockState",
    "ContainerState",
    "TrapState",
    "HazardState",
    "LightEmission",
    "Area",
    "AreaEffect",
    "Duration",
    "SpreadBehavior",
    "Trigger",
    "DetectionDifficulty",
    "DisarmDifficulty",
    "Payload",
  ],

  social: [
    "SocialDisposition",
    "Attitude",
    "Trust",
    "Loyalty",
    "Hostility",
    "ConversationState",
    "DialogueProfile",
    "Secrets",
    "Rumors",
    "Needs",
    "Wants",
    "Promises",
    "Debts",
    "Contacts",
    "RoleplayHooks",
  ],

  travelAndExploration: [
    "TravelMode",
    "TravelPace",
    "TravelRoute",
    "TravelProgress",
    "NavigationState",
    "LostState",
    "CampingState",
    "ForagingState",
    "FoodSupply",
    "WaterSupply",
    "ShelterState",
    "DiscoveryState",
    "ExplorationProgress",
    "MapKnowledge",
    "VisitedLocations",
  ],

  procedural: [
    "GeneratorDefinition",
    "RandomTable",
    "WeightedEntries",
    "GenerationContext",
    "GenerationConstraints",
    "OracleState",
    "QuestionState",
    "RandomEventState",
    "EncounterGenerator",
    "NpcGenerator",
    "QuestGenerator",
    "DungeonGenerator",
    "WildernessGenerator",
    "LootGenerator",
    "MerchantGenerator",
  ],

  rulesAndRuntime: [
    "RuleReferences",
    "RuleOverrides",
    "RegisteredTriggers",
    "RegisteredModifiers",
    "RegisteredActions",
    "RegisteredReactions",
    "RegisteredResources",
    "ValidationState",
    "DirtyComponents",
    "DerivedValues",
    "EventSubscriptions",
    "EventHistory",
    "PendingEvents",
    "CommandQueue",
    "IntentQueue",
  ],
};

export const OPERATIONS = {
  componentLifecycle: [
    "ADD_COMPONENT",
    "REMOVE_COMPONENT",
    "REPLACE_COMPONENT",
    "ENABLE_COMPONENT",
    "DISABLE_COMPONENT",
    "MERGE_COMPONENT",
    "RESET_COMPONENT",
    "CLONE_COMPONENT",
  ],

  valueMutation: [
    "SET_VALUE",
    "SET_IF_ABSENT",
    "CLEAR_VALUE",
    "COPY_VALUE",
    "MOVE_VALUE",
    "SWAP_VALUE",
    "ADD_VALUE",
    "SUBTRACT_VALUE",
    "MULTIPLY_VALUE",
    "DIVIDE_VALUE",
    "MIN_VALUE",
    "MAX_VALUE",
    "CLAMP_VALUE",
    "INCREMENT_VALUE",
    "DECREMENT_VALUE",
    "TOGGLE_VALUE",
  ],

  collectionMutation: [
    "ADD_ENTRY",
    "ADD_UNIQUE_ENTRY",
    "REMOVE_ENTRY",
    "REPLACE_ENTRY",
    "MERGE_ENTRY",
    "CLEAR_ENTRIES",
    "SORT_ENTRIES",
    "MOVE_ENTRY",
    "COPY_ENTRY",
    "INCREMENT_ENTRY",
    "DECREMENT_ENTRY",
  ],

  tagsAndClassification: [
    "ADD_TAG",
    "REMOVE_TAG",
    "REPLACE_TAG",
    "ADD_TYPE",
    "REMOVE_TYPE",
    "ADD_SUBTYPE",
    "REMOVE_SUBTYPE",
    "SET_ALIGNMENT",
    "SET_DISPOSITION",
  ],

  registration: [
    "REGISTER_ACTION",
    "UNREGISTER_ACTION",
    "REGISTER_BONUS_ACTION",
    "UNREGISTER_BONUS_ACTION",
    "REGISTER_REACTION",
    "UNREGISTER_REACTION",
    "REGISTER_LEGENDARY_ACTION",
    "UNREGISTER_LEGENDARY_ACTION",
    "REGISTER_LAIR_ACTION",
    "UNREGISTER_LAIR_ACTION",
    "REGISTER_TRIGGER",
    "UNREGISTER_TRIGGER",
    "REGISTER_MODIFIER",
    "UNREGISTER_MODIFIER",
    "REGISTER_EFFECT",
    "UNREGISTER_EFFECT",
    "REGISTER_RESOURCE",
    "UNREGISTER_RESOURCE",
    "REGISTER_RULE",
    "UNREGISTER_RULE",
  ],

  resources: [
    "GRANT_RESOURCE",
    "REMOVE_RESOURCE",
    "SET_RESOURCE",
    "SPEND_RESOURCE",
    "RESTORE_RESOURCE",
    "DRAIN_RESOURCE",
    "CHANGE_RESOURCE_MAXIMUM",
    "INCREASE_RESOURCE_MAXIMUM",
    "DECREASE_RESOURCE_MAXIMUM",
    "LOCK_RESOURCE",
    "UNLOCK_RESOURCE",
    "RESET_RESOURCE",
    "RECHARGE_RESOURCE",
  ],

  healthAndDamage: [
    "DEAL_DAMAGE",
    "HEAL_DAMAGE",
    "SET_HIT_POINTS",
    "CHANGE_MAXIMUM_HIT_POINTS",
    "GRANT_TEMPORARY_HIT_POINTS",
    "REMOVE_TEMPORARY_HIT_POINTS",
    "ROLL_HIT_DICE",
    "SPEND_HIT_DIE",
    "RESTORE_HIT_DICE",
    "APPLY_DAMAGE_RESISTANCE",
    "APPLY_DAMAGE_VULNERABILITY",
    "APPLY_DAMAGE_IMMUNITY",
    "REMOVE_DAMAGE_RESISTANCE",
    "REMOVE_DAMAGE_VULNERABILITY",
    "REMOVE_DAMAGE_IMMUNITY",
    "SET_DEATH_STATE",
    "ADD_DEATH_SAVE_SUCCESS",
    "ADD_DEATH_SAVE_FAILURE",
    "RESET_DEATH_SAVES",
    "STABILIZE_CREATURE",
  ],

  conditionsAndEffects: [
    "APPLY_CONDITION",
    "REMOVE_CONDITION",
    "REPLACE_CONDITION",
    "STACK_CONDITION",
    "CLEAR_CONDITIONS",
    "APPLY_EFFECT",
    "REMOVE_EFFECT",
    "SUSPEND_EFFECT",
    "RESUME_EFFECT",
    "EXTEND_EFFECT_DURATION",
    "REDUCE_EFFECT_DURATION",
    "STACK_EFFECT",
    "DISPEL_EFFECT",
    "EXPIRE_EFFECT",
    "TRANSFER_EFFECT",
    "APPLY_CURSE",
    "REMOVE_CURSE",
    "APPLY_DISEASE",
    "REMOVE_DISEASE",
    "APPLY_POISON",
    "REMOVE_POISON",
  ],

  modifiers: [
    "ADD_MODIFIER",
    "REMOVE_MODIFIER",
    "ENABLE_MODIFIER",
    "DISABLE_MODIFIER",
    "STACK_MODIFIER",
    "REPLACE_MODIFIER",
    "RECALCULATE_MODIFIERS",
    "MARK_DERIVED_VALUE_DIRTY",
    "RECALCULATE_DERIVED_VALUE",
    "RECALCULATE_ALL_DERIVED_VALUES",
  ],

  grantsAndProgression: [
    "APPLY_GRANT",
    "REMOVE_GRANT",
    "REAPPLY_GRANT",
    "VALIDATE_GRANT",
    "RECORD_APPLIED_GRANT",
    "REMOVE_APPLIED_GRANT_RECORD",
    "ADD_LEVEL",
    "REMOVE_LEVEL",
    "SET_LEVEL",
    "ADD_CLASS_LEVEL",
    "REMOVE_CLASS_LEVEL",
    "SET_CLASS_LEVEL",
    "ADD_EXPERIENCE",
    "REMOVE_EXPERIENCE",
    "SET_EXPERIENCE",
    "ADD_MILESTONE",
    "REMOVE_MILESTONE",
    "SET_CHALLENGE_RATING",
  ],

  choices: [
    "ADD_CHOICE",
    "REMOVE_CHOICE",
    "RESOLVE_CHOICE",
    "REOPEN_CHOICE",
    "VALIDATE_CHOICE",
    "INVALIDATE_CHOICE",
    "ADD_CHOICE_OPTION",
    "REMOVE_CHOICE_OPTION",
    "SELECT_CHOICE_OPTION",
    "DESELECT_CHOICE_OPTION",
    "COMPLETE_BUILD",
    "MARK_BUILD_INCOMPLETE",
  ],

  itemsAndInventory: [
    "CREATE_ITEM",
    "DESTROY_ITEM",
    "CLONE_ITEM",
    "GRANT_ITEM",
    "REMOVE_ITEM",
    "TRANSFER_ITEM",
    "ADD_ITEM_TO_INVENTORY",
    "REMOVE_ITEM_FROM_INVENTORY",
    "MOVE_ITEM_TO_CONTAINER",
    "REMOVE_ITEM_FROM_CONTAINER",
    "EQUIP_ITEM",
    "UNEQUIP_ITEM",
    "ATTUNE_ITEM",
    "UNATTUNE_ITEM",
    "CONSUME_ITEM",
    "RESTORE_ITEM_CHARGES",
    "SPEND_ITEM_CHARGE",
    "SET_ITEM_CHARGES",
    "DAMAGE_ITEM",
    "REPAIR_ITEM",
    "CHANGE_ITEM_OWNER",
    "ADD_CURRENCY",
    "REMOVE_CURRENCY",
    "TRANSFER_CURRENCY",
  ],

  spellsAndMagic: [
    "LEARN_SPELL",
    "FORGET_SPELL",
    "PREPARE_SPELL",
    "UNPREPARE_SPELL",
    "ADD_SPELL_TO_SPELLBOOK",
    "REMOVE_SPELL_FROM_SPELLBOOK",
    "GRANT_SPELL_SLOT",
    "REMOVE_SPELL_SLOT",
    "SPEND_SPELL_SLOT",
    "RESTORE_SPELL_SLOT",
    "CAST_SPELL",
    "COUNTER_SPELL",
    "DISPEL_MAGIC",
    "START_CONCENTRATION",
    "END_CONCENTRATION",
    "BREAK_CONCENTRATION",
    "ADD_MAGIC_CHARGE",
    "SPEND_MAGIC_CHARGE",
    "RESTORE_MAGIC_CHARGE",
  ],

  combat: [
    "START_COMBAT",
    "END_COMBAT",
    "ADD_COMBATANT",
    "REMOVE_COMBATANT",
    "ROLL_INITIATIVE",
    "SET_INITIATIVE",
    "BUILD_TURN_ORDER",
    "ADVANCE_TURN",
    "ADVANCE_ROUND",
    "START_TURN",
    "END_TURN",
    "RESET_ACTION_ECONOMY",
    "SPEND_ACTION",
    "SPEND_BONUS_ACTION",
    "SPEND_REACTION",
    "SPEND_MOVEMENT",
    "RESTORE_ACTION",
    "RESTORE_BONUS_ACTION",
    "RESTORE_REACTION",
    "RESTORE_MOVEMENT",
    "DECLARE_ATTACK",
    "RESOLVE_ATTACK",
    "ROLL_ATTACK",
    "ROLL_DAMAGE",
    "APPLY_DODGE",
    "REMOVE_DODGE",
    "APPLY_DASH",
    "APPLY_DISENGAGE",
    "APPLY_HELP",
    "APPLY_HIDE",
    "APPLY_READY",
    "APPLY_SEARCH",
    "SET_TARGET",
    "CLEAR_TARGET",
    "ADD_TARGET",
    "REMOVE_TARGET",
    "KNOCK_PRONE",
    "STAND_UP",
    "GRAPPLE",
    "ESCAPE_GRAPPLE",
    "SHOVE",
  ],

  movementAndPosition: [
    "SET_POSITION",
    "MOVE_ENTITY",
    "TELEPORT_ENTITY",
    "SET_FACING",
    "ROTATE_ENTITY",
    "ENTER_ZONE",
    "LEAVE_ZONE",
    "CHANGE_ZONE",
    "MOUNT_ENTITY",
    "DISMOUNT_ENTITY",
    "SET_MOVEMENT_MODE",
    "ADD_MOVEMENT_MODE",
    "REMOVE_MOVEMENT_MODE",
    "CHANGE_SPEED",
    "CHANGE_REACH",
    "CHANGE_SPACE_OCCUPIED",
  ],

  controlAndIntent: [
    "SET_CONTROLLER",
    "ASSIGN_PLAYER_CONTROL",
    "ASSIGN_AI_CONTROL",
    "REMOVE_CONTROL",
    "CREATE_INTENT",
    "QUEUE_INTENT",
    "DEQUEUE_INTENT",
    "VALIDATE_INTENT",
    "ACCEPT_INTENT",
    "REJECT_INTENT",
    "RESOLVE_INTENT",
    "CANCEL_INTENT",
    "REPLACE_INTENT",
    "RECORD_INTENT",
    "CLEAR_INTENT_HISTORY",
  ],

  ai: [
    "ADD_GOAL",
    "REMOVE_GOAL",
    "SET_ACTIVE_GOAL",
    "COMPLETE_GOAL",
    "FAIL_GOAL",
    "ADD_KNOWN_ENTITY",
    "REMOVE_KNOWN_ENTITY",
    "ADD_KNOWN_THREAT",
    "REMOVE_KNOWN_THREAT",
    "ADD_KNOWN_ALLY",
    "REMOVE_KNOWN_ALLY",
    "UPDATE_THREAT_ASSESSMENT",
    "UPDATE_MORALE",
    "SET_BEHAVIOR_PROFILE",
    "SET_TACTICS",
    "SET_TARGET_PRIORITY",
    "GENERATE_AI_INTENT",
  ],

  scenesAndWorld: [
    "CREATE_SCENE",
    "DESTROY_SCENE",
    "START_SCENE",
    "END_SCENE",
    "PAUSE_SCENE",
    "RESUME_SCENE",
    "ADD_SCENE_PARTICIPANT",
    "REMOVE_SCENE_PARTICIPANT",
    "SET_SCENE_TYPE",
    "SET_SCENE_STATE",
    "ADD_SCENE_RULE",
    "REMOVE_SCENE_RULE",
    "CREATE_LOCATION",
    "CREATE_ZONE",
    "CREATE_OBJECT",
    "DESTROY_OBJECT",
    "CREATE_HAZARD",
    "REMOVE_HAZARD",
    "CREATE_TRAP",
    "DISARM_TRAP",
    "TRIGGER_TRAP",
    "OPEN_DOOR",
    "CLOSE_DOOR",
    "LOCK_DOOR",
    "UNLOCK_DOOR",
    "OPEN_CONTAINER",
    "CLOSE_CONTAINER",
    "SET_WEATHER",
    "SET_TIME_OF_DAY",
    "SET_LIGHT_LEVEL",
  ],

  social: [
    "CHANGE_ATTITUDE",
    "CHANGE_TRUST",
    "CHANGE_LOYALTY",
    "CHANGE_HOSTILITY",
    "ADD_RELATIONSHIP",
    "REMOVE_RELATIONSHIP",
    "CHANGE_REPUTATION",
    "ADD_SECRET",
    "REVEAL_SECRET",
    "ADD_RUMOR",
    "REMOVE_RUMOR",
    "ADD_PROMISE",
    "FULFILL_PROMISE",
    "BREAK_PROMISE",
    "ADD_DEBT",
    "PAY_DEBT",
    "START_CONVERSATION",
    "END_CONVERSATION",
  ],

  travelAndExploration: [
    "START_TRAVEL",
    "PAUSE_TRAVEL",
    "RESUME_TRAVEL",
    "END_TRAVEL",
    "SET_TRAVEL_ROUTE",
    "SET_TRAVEL_PACE",
    "ADVANCE_TRAVEL",
    "CONSUME_FOOD",
    "CONSUME_WATER",
    "ADD_FOOD",
    "ADD_WATER",
    "START_CAMP",
    "END_CAMP",
    "START_FORAGING",
    "END_FORAGING",
    "DISCOVER_LOCATION",
    "VISIT_LOCATION",
    "LEAVE_LOCATION",
    "REVEAL_MAP_AREA",
    "ADD_MAP_KNOWLEDGE",
    "REMOVE_MAP_KNOWLEDGE",
  ],

  proceduralGeneration: [
    "ROLL_RANDOM_TABLE",
    "ROLL_WEIGHTED_TABLE",
    "GENERATE_RANDOM_EVENT",
    "GENERATE_ENCOUNTER",
    "GENERATE_NPC",
    "GENERATE_QUEST",
    "GENERATE_DUNGEON",
    "GENERATE_WILDERNESS",
    "GENERATE_LOOT",
    "GENERATE_MERCHANT",
    "ASK_ORACLE",
    "RESOLVE_ORACLE_ANSWER",
    "ADD_GENERATION_CONTEXT",
    "REMOVE_GENERATION_CONTEXT",
    "ADD_GENERATION_CONSTRAINT",
    "REMOVE_GENERATION_CONSTRAINT",
  ],

  eventsAndRuntime: [
    "EMIT_EVENT",
    "QUEUE_EVENT",
    "CANCEL_EVENT",
    "RESOLVE_EVENT",
    "REGISTER_EVENT_LISTENER",
    "UNREGISTER_EVENT_LISTENER",
    "ADD_EVENT_HISTORY_ENTRY",
    "CLEAR_EVENT_HISTORY",
    "QUEUE_COMMAND",
    "DEQUEUE_COMMAND",
    "EXECUTE_COMMAND",
    "CANCEL_COMMAND",
    "VALIDATE_ENTITY",
    "VALIDATE_COMPONENT",
    "VALIDATE_STATE",
    "MARK_COMPONENT_DIRTY",
    "CLEAR_COMPONENT_DIRTY",
    "SERIALIZE_ENTITY",
    "DESERIALIZE_ENTITY",
    "MIGRATE_ENTITY",
  ],
};

export const ALL_COMPONENTS = Object.values(COMPONENTS).flat();
export const ALL_OPERATIONS = Object.values(OPERATIONS).flat();
